// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: proto/deckhouse/v1/prompts.proto

package deckhousev1

import (
	context "context"
	errors "errors"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
)

// File_proto_deckhouse_v1_prompts_protoPromptHandler defines handlers for MCP prompts in proto/deckhouse/v1/prompts.proto.
type File_proto_deckhouse_v1_prompts_protoPromptHandler interface {
	DiagnoseClusterHealth(ctx context.Context, req *DiagnoseClusterHealth) ([]mcpruntime.PromptMessage, error)
	TriageUnhealthyPods(ctx context.Context, req *TriageUnhealthyPods) ([]mcpruntime.PromptMessage, error)
	InvestigateNode(ctx context.Context, req *InvestigateNode) ([]mcpruntime.PromptMessage, error)
	PrepareDeckhouseUpgrade(ctx context.Context, req *PrepareDeckhouseUpgrade) ([]mcpruntime.PromptMessage, error)
	AddWorkerNode(ctx context.Context, req *AddWorkerNode) ([]mcpruntime.PromptMessage, error)
}

// RegisterFile_proto_deckhouse_v1_prompts_protoPrompts registers generated MCP prompts for File_proto_deckhouse_v1_prompts_proto.
func RegisterFile_proto_deckhouse_v1_prompts_protoPrompts(server *mcpruntime.Server, impl File_proto_deckhouse_v1_prompts_protoPromptHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterFile_proto_deckhouse_v1_prompts_protoPrompts: impl is nil")
	}
	server.AddPrompt(&mcpruntime.Prompt{
		Name:        "diagnose_cluster_health",
		Title:       "Diagnose cluster health",
		Description: "Assess overall cluster health: node readiness, NodeGroups, unhealthy pods, errored modules, and pending releases.",
		Arguments: []mcpruntime.PromptArgument{
			{Name: "focus", Description: "Optional area to focus on: nodes, modules, releases, or pods. When empty, assess everything.", Required: false},
		},
	}, func(ctx context.Context, req *mcpruntime.GetPromptRequest) (*mcpruntime.GetPromptResult, error) {
		msg := &DiagnoseClusterHealth{}
		if err := mcpruntime.ParsePromptArguments(req.Arguments, msg, []string{}); err != nil {
			return nil, err
		}
		result, err := impl.DiagnoseClusterHealth(ctx, msg)
		if err != nil {
			return nil, err
		}
		return &mcpruntime.GetPromptResult{Messages: result}, nil
	})
	server.AddPrompt(&mcpruntime.Prompt{
		Name:        "triage_unhealthy_pods",
		Title:       "Triage unhealthy pods",
		Description: "Find unhealthy pods and drill into logs and events to determine root cause.",
		Arguments: []mcpruntime.PromptArgument{
			{Name: "namespace", Description: "Optional namespace to restrict triage to. When empty, scan all namespaces.", Required: false},
		},
	}, func(ctx context.Context, req *mcpruntime.GetPromptRequest) (*mcpruntime.GetPromptResult, error) {
		msg := &TriageUnhealthyPods{}
		if err := mcpruntime.ParsePromptArguments(req.Arguments, msg, []string{}); err != nil {
			return nil, err
		}
		result, err := impl.TriageUnhealthyPods(ctx, msg)
		if err != nil {
			return nil, err
		}
		return &mcpruntime.GetPromptResult{Messages: result}, nil
	})
	server.AddPrompt(&mcpruntime.Prompt{
		Name:        "investigate_node",
		Title:       "Investigate a node",
		Description: "Deep-dive into a single node: status, conditions, resources, recent events, and kubelet logs.",
		Arguments: []mcpruntime.PromptArgument{
			{Name: "name", Description: "Name of the node to investigate.", Required: true},
		},
	}, func(ctx context.Context, req *mcpruntime.GetPromptRequest) (*mcpruntime.GetPromptResult, error) {
		msg := &InvestigateNode{}
		if err := mcpruntime.ParsePromptArguments(req.Arguments, msg, []string{
			"name",
		}); err != nil {
			return nil, err
		}
		result, err := impl.InvestigateNode(ctx, msg)
		if err != nil {
			return nil, err
		}
		return &mcpruntime.GetPromptResult{Messages: result}, nil
	})
	server.AddPrompt(&mcpruntime.Prompt{
		Name:        "prepare_deckhouse_upgrade",
		Title:       "Prepare for a Deckhouse upgrade",
		Description: "Review pending DeckhouseReleases, current cluster health, and module readiness before approving an upgrade.",
		Arguments: []mcpruntime.PromptArgument{
			{Name: "targetVersion", Description: "Optional target Deckhouse version, e.g. 'v1.74.0'. When empty, consider the next pending release.", Required: false},
		},
	}, func(ctx context.Context, req *mcpruntime.GetPromptRequest) (*mcpruntime.GetPromptResult, error) {
		msg := &PrepareDeckhouseUpgrade{}
		if err := mcpruntime.ParsePromptArguments(req.Arguments, msg, []string{}); err != nil {
			return nil, err
		}
		result, err := impl.PrepareDeckhouseUpgrade(ctx, msg)
		if err != nil {
			return nil, err
		}
		return &mcpruntime.GetPromptResult{Messages: result}, nil
	})
	server.AddPrompt(&mcpruntime.Prompt{
		Name:        "add_worker_node",
		Title:       "Add a worker node",
		Description: "Step-by-step guide to add a worker node to a NodeGroup using a StaticInstance and SSH credentials.",
		Arguments: []mcpruntime.PromptArgument{
			{Name: "nodeGroup", Description: "Name of the NodeGroup the new worker node should join.", Required: true},
			{Name: "address", Description: "Optional SSH-reachable IP address or hostname of the machine to add.", Required: false},
		},
	}, func(ctx context.Context, req *mcpruntime.GetPromptRequest) (*mcpruntime.GetPromptResult, error) {
		msg := &AddWorkerNode{}
		if err := mcpruntime.ParsePromptArguments(req.Arguments, msg, []string{
			"nodeGroup",
		}); err != nil {
			return nil, err
		}
		result, err := impl.AddWorkerNode(ctx, msg)
		if err != nil {
			return nil, err
		}
		return &mcpruntime.GetPromptResult{Messages: result}, nil
	})
	return nil
}
