// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: proto/deckhouse/v1/resources.proto

package deckhousev1

import (
	context "context"
	errors "errors"
	fmt "fmt"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
)

// File_proto_deckhouse_v1_resources_protoResourceHandler defines handlers for MCP resources in proto/deckhouse/v1/resources.proto.
type File_proto_deckhouse_v1_resources_protoResourceHandler interface {
	ReadClusterStatus(ctx context.Context) (*ClusterStatus, error)
	ReadClusterConfiguration(ctx context.Context) (*ClusterConfiguration, error)
	ReadNodeList(ctx context.Context) (*NodeList, error)
	ReadModuleList(ctx context.Context) (*ModuleList, error)
	ReadDeckhouseReleaseList(ctx context.Context) (*DeckhouseReleaseList, error)
	ListNodes(ctx context.Context) ([]mcpruntime.Resource, error)
	ReadNode(ctx context.Context, name string) (*Node, error)
	ListModules(ctx context.Context) ([]mcpruntime.Resource, error)
	ReadModule(ctx context.Context, name string) (*Module, error)
}

// RegisterFile_proto_deckhouse_v1_resources_protoResources registers generated MCP resources for File_proto_deckhouse_v1_resources_proto.
func RegisterFile_proto_deckhouse_v1_resources_protoResources(ctx context.Context, server *mcpruntime.Server, impl File_proto_deckhouse_v1_resources_protoResourceHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterFile_proto_deckhouse_v1_resources_protoResources: impl is nil")
	}
	resolvedOpts := mcpruntime.ResolveOptions("", opts)
	{
		name := "cluster_status"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		server.AddResource(&mcpruntime.Resource{
			Name:        name,
			URI:         "deckhouse://cluster/status",
			Description: "Aggregated cluster status: node readiness counts, per-NodeGroup health, errored ModuleConfigs, pending DeckhouseReleases, total unhealthy pod count, and the deployed Deckhouse version.",
			MIMEType:    "application/json",
		}, func(ctx context.Context, req *mcpruntime.ReadResourceRequest) (*mcpruntime.ReadResourceResult, error) {
			result, err := impl.ReadClusterStatus(ctx)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent("deckhouse://cluster/status", "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcpruntime.ReadResourceResult{Contents: contents}, nil
		})
	}

	{
		name := "cluster_configuration"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		server.AddResource(&mcpruntime.Resource{
			Name:        name,
			URI:         "deckhouse://cluster/configuration",
			Description: "Current Deckhouse ClusterConfiguration (cluster type, Kubernetes version, pod/service subnets, cloud provider).",
			MIMEType:    "application/json",
		}, func(ctx context.Context, req *mcpruntime.ReadResourceRequest) (*mcpruntime.ReadResourceResult, error) {
			result, err := impl.ReadClusterConfiguration(ctx)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent("deckhouse://cluster/configuration", "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcpruntime.ReadResourceResult{Contents: contents}, nil
		})
	}

	{
		name := "nodes"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		server.AddResource(&mcpruntime.Resource{
			Name:        name,
			URI:         "deckhouse://nodes",
			Description: "All cluster nodes with status, role, internal IP, OS image, kubelet version, age, and NodeGroup.",
			MIMEType:    "application/json",
		}, func(ctx context.Context, req *mcpruntime.ReadResourceRequest) (*mcpruntime.ReadResourceResult, error) {
			result, err := impl.ReadNodeList(ctx)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent("deckhouse://nodes", "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcpruntime.ReadResourceResult{Contents: contents}, nil
		})
	}

	{
		name := "modules"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		server.AddResource(&mcpruntime.Resource{
			Name:        name,
			URI:         "deckhouse://modules",
			Description: "All Deckhouse modules with enabled state, phase, and source.",
			MIMEType:    "application/json",
		}, func(ctx context.Context, req *mcpruntime.ReadResourceRequest) (*mcpruntime.ReadResourceResult, error) {
			result, err := impl.ReadModuleList(ctx)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent("deckhouse://modules", "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcpruntime.ReadResourceResult{Contents: contents}, nil
		})
	}

	{
		name := "releases"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		server.AddResource(&mcpruntime.Resource{
			Name:        name,
			URI:         "deckhouse://releases",
			Description: "All DeckhouseRelease resources with version, phase (Pending/Deployed/Superseded/Skipped), approval status, and transition time.",
			MIMEType:    "application/json",
		}, func(ctx context.Context, req *mcpruntime.ReadResourceRequest) (*mcpruntime.ReadResourceResult, error) {
			result, err := impl.ReadDeckhouseReleaseList(ctx)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent("deckhouse://releases", "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcpruntime.ReadResourceResult{Contents: contents}, nil
		})
	}

	{
		name := "node"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		instances, err := impl.ListNodes(ctx)
		if err != nil {
			return fmt.Errorf("RegisterFile_proto_deckhouse_v1_resources_protoResources: listing node: %w", err)
		}
		readHandler := func(ctx context.Context, req *mcpruntime.ReadResourceRequest) (*mcpruntime.ReadResourceResult, error) {
			params, err := mcpruntime.ExtractURIParams(req.URI, "deckhouse://nodes/{name}")
			if err != nil {
				return nil, err
			}
			name := params["name"]
			result, err := impl.ReadNode(ctx, name)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent(req.URI, "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcpruntime.ReadResourceResult{Contents: contents}, nil
		}
		for i := range instances {
			server.AddResource(&instances[i], readHandler)
		}
		server.AddResourceTemplate(&mcpruntime.ResourceTemplate{
			Name:        name,
			URITemplate: "deckhouse://nodes/{name}",
			Description: "Detailed information about a single cluster node by name: conditions, allocatable/capacity resources, StaticInstance phase, and recent events.",
			MIMEType:    "application/json",
		}, readHandler)
	}

	{
		name := "module"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		instances, err := impl.ListModules(ctx)
		if err != nil {
			return fmt.Errorf("RegisterFile_proto_deckhouse_v1_resources_protoResources: listing module: %w", err)
		}
		readHandler := func(ctx context.Context, req *mcpruntime.ReadResourceRequest) (*mcpruntime.ReadResourceResult, error) {
			params, err := mcpruntime.ExtractURIParams(req.URI, "deckhouse://modules/{name}")
			if err != nil {
				return nil, err
			}
			name := params["name"]
			result, err := impl.ReadModule(ctx, name)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent(req.URI, "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcpruntime.ReadResourceResult{Contents: contents}, nil
		}
		for i := range instances {
			server.AddResource(&instances[i], readHandler)
		}
		server.AddResourceTemplate(&mcpruntime.ResourceTemplate{
			Name:        name,
			URITemplate: "deckhouse://modules/{name}",
			Description: "The ModuleConfig for a single Deckhouse module by name: enabled state, version, and settings.",
			MIMEType:    "application/json",
		}, readHandler)
	}

	return nil
}
